<a href="https://colab.research.google.com/github/Prabhu-ML/ML-Algorithms/blob/Data-Preprocessing-Ex/Data_Prep1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [ ]:
df=pd.read_csv('melb_data.csv')

In [ ]:
df.head(2)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0

In [ ]:
df.shape

(13580, 21)

In [ ]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [ ]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [ ]:
y=df['Price']
X=df.drop('Price',axis=1)

In [ ]:
y.shape

(13580,)

In [ ]:
X.shape

(13580, 20)

In [ ]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [ ]:
X.drop(columns=['SellerG','Lattitude',
       'Longtitude','Propertycount'],axis=1,inplace=True)

In [ ]:
X.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Method', 'Date', 'Distance',
       'Postcode', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea',
       'YearBuilt', 'CouncilArea', 'Regionname'],
      dtype='object')

In [ ]:
X['Date']=pd.to_datetime(X['Date'],errors='coerce',dayfirst=True)
X['Day']=X['Date'].dt.day
X['Month']=X['Date'].dt.month
X['Year']=X['Date'].dt.year

In [ ]:
X.head(2)

,Suburb,Address,Rooms,Type,Method,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Regionname,Day,Month,Year
0,Abbotsford,85 Turner St,2,h,S,2016-12-03,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra,Northern Metropolitan,3,12,2016
1,Abbotsford,25 Bloomburg St,2,h,S,2016-02-04,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra,Northern Metropolitan,4,2,2016

In [ ]:
X.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Method', 'Date', 'Distance',
       'Postcode', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea',
       'YearBuilt', 'CouncilArea', 'Regionname', 'Day', 'Month', 'Year'],
      dtype='object')

In [ ]:
num_X=X.select_dtypes(include='number')
cat_X=X.select_dtypes(exclude='number')

In [ ]:
num_tranformations=Pipeline(steps=[("imputer",SimpleImputer(strategy="median")), ("scaling",StandardScaler())])
cat_transformations=Pipeline(steps=[("imputer",SimpleImputer(strategy="most_frequent")),("onehot",OneHotEncoder(handle_unknown="ignore"))])

In [ ]:
from sklearn.compose import ColumnTransformer
preprocessor=ColumnTransformer(transformers=[("num",num_tranformations,num_X.columns),("cat",cat_transformations,cat_X.columns)])
preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 Index(['Rooms', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'Day', 'Month', 'Year'],
      dtype='object')),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 Index(['Suburb', 'Address', 'Type', 'Method', 'Date', 'CouncilArea',
       'Regionname'],
      dtype='object'))])

In [ ]:
num_X

,Rooms,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Day,Month,Year
0,2,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,3,12,2016
1,2,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,4,2,2016
2,3,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,4,3,2017
3,3,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,4,3,2017
4,4,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,4,6,2016
...,...,...,...,...,...,...,...,...,...,...,...,...
13575,4,16.7,3150.0,4.0,2.0,2.0,652.0,NaN,1981.0,26,8,2017
13576,3,6.8,3016.0,3.0,2.0,2.0,333.0,133.0,1995.0,26,8,2017
13577,3,6.8,3016.0,3.0,2.0,4.0,436.0,NaN,1997.0,26,8,2017
13578,4,6.8,3016.0,4.0,1.0,5.0,866.0,157.0,1920.0,26,8,2017
13579,4,6.3,3013.0,4.0,1.0,1.0,362.0,112.0,1920.0,26,8,2017

In [ ]:
X_train,y_train, X_test,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
X_train.shape

(10864, 19)

In [ ]:
from sklearn import linear_model
reg=linear_model.LinearRegression()
reg.fit(df[['Landsize']],df.Price)

LinearRegression()

In [ ]:
reg.predict([[35000]])

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([1282634.78507106])

In [ ]:
import pandas as pd

# Input the new value for prediction as a DataFrame with the original feature name
new_landsize_df = pd.DataFrame([[35000]], columns=['Landsize'])

# Make the prediction
prediction = reg.predict(new_landsize_df)

print(f"Predicted price for Landsize 35000: {prediction[0]:,.2f}")

Predicted price for Landsize 35000: 1,282,634.79